name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: E2E run on Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: E2E run on Firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
